#! /bin/sh -e

package=$1
shift

sourcedir=$(alocate "$package")
builddir=$(alocate -b "$sourcedir")

poky=$(alocate "tools/poky")
OEROOT=$poky
BDIR=$builddir
. $poky/oe-init-build-env

cd "$builddir"
"$@"

